[project]
name = "rag-production-grade"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "celery>=5.6.3",
    "docling>=2.120.2",
    "logfire[celery,fastapi,httpx,system-metrics]>=4.40.0",
    "openai>=3.1.0",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "redis>=8.1.0",
    "sentence-transformers>=5.7.0",
    "streamlit>=1.61.1",
]
